pipeline{
  agent any
  stages{
    stage('Checkout Code'){
      steps{
        git "https://github.com/Chaitraputtabudhi/Projects/edit/main/MERN-Project"
      }
    }
    stage('Build'){
      steps{
        sh 'echo "building the application."'
      }
    }
    stage('Test'){
      steps{
        sh 'echo "Testing the application"'
      }
    }
    stage('Deploy'){
      steps{
        sh 'echo "Deploying the application"'
      }
    }
  }
}
post{
  success{
    bat 'echo "build successful"'
  }
  failure{
    bat 'echo "build failed"'
  }
}
