pipeline {
    agent any
    environment {
        IMAGE_NAME = 'chaitraputtabudhi/mern-project'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Chaitraputtabudhi/Projects.git',
                    credentialsId: 'Chaitraputtabudhi'
            }
        }

        stage('Build Docker Image') {
            steps {
              sh "echo 'build docker image'"
            }
        }

        stage('Push to Dockerhub') {
            steps {
               sh 'echo "push to dockerhub"'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying the application..."'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
        }
        success {
            echo 'Pipeline finished successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
