pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Chaitraputtabudhi/Projects.git',
                    credentialsId: 'Chaitraputtabudhi'
            }
        }

        stage('Build') {
            steps {
                sh 'echo building the application.'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Testing the application'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo Deploying the application'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
        }
        success {
            echo 'Pipeline finished successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
